name: Deploy to GitHub Pages from master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 确保能访问完整 Git 历史以进行分支操作

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync master to gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard origin/master
          git push origin gh-pages --force

      - name: Deploy GitHub Pages (if needed)
        run: echo "Deployment complete. GitHub Pages will deploy gh-pages branch automatically."
